# ===========================
# 服务器端口配置
# ===========================
server:
  # 官网Web服务端口
  webPort: 8100
  # 用户服务端口
  userPort: 8200
  # WebSocket服务端口
  wsPort: 9000
  # 限流队列容量
  queueCapacity: 1000
  # 限流突发容量
  suddenCapacity: 2000

# ===========================
# MySQL数据库配置
# ===========================
mysql:
  # 数据库地址
  address: "149.104.25.199:3306"
  # 数据库名称
  database: "shop"
  # 数据库用户
  user: "shop"
  # 数据库密码
  password: "@Tt37233535"

# ===========================
# Redis配置
# ===========================
redis:
  # Redis服务器地址
  address: "localhost:6379"
  # 密码，没有则为空
  password: ""
  # 默认数据库
  db: 0
